# Generated by Django 3.2.1 on 2021-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=150)),
                ('location_address', models.CharField(max_length=255)),
                ('location_memories', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'db_table': 'memories',
                'managed': True,
            },
        ),
    ]
