# Generated by Django 3.2.1 on 2021-05-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorymodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='memorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
